######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 7 16:40:39 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += memorylocationtest.cpp ../../memorylocation.cpp
