######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 16 17:38:04 2013
######################################################################

TEMPLATE = subdirs
SUBDIRS += freeems megasquirt
