######################################################################
# Automatically generated by qmake (2.01a) Sat Feb 16 17:38:04 2013
######################################################################

TEMPLATE = subdirs
isEmpty(SUBDIR_LIST) {
SUBDIR_LIST = freeems
}
SUBDIRS += $$SUBDIR_LIST
