######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 7 17:02:59 2012
######################################################################

TEMPLATE = subdirs
SUBDIRS += memorymetadatatest memorylocationtest
